// Mock data for ImmoHero

const MEDIA_CATALOG = [
  { id: 'photo', name: 'Fotografie', icon: 'camera', price: 249, duration: '1–2 Std.', desc: '25–40 bearbeitete Objektfotos, HDR, Retusche', popular: true },
  { id: 'drone', name: 'Drohne / Luftbild', icon: 'drone', price: 189, duration: '45 Min.', desc: '4K-Luftaufnahmen & Umgebungsshots', popular: true },
  { id: 'tour360', name: '360°-Tour', icon: 'sphere', price: 349, duration: '2 Std.', desc: 'Interaktive Rundgänge, Web-eingebettet' },
  { id: 'video', name: 'Video / Reel', icon: 'play', price: 449, duration: '2–3 Std.', desc: 'Cinematischer Kurzfilm, 60–90 Sek.' },
  { id: 'plan2d', name: 'Grundriss 2D', icon: 'plan', price: 79, duration: 'Digital', desc: 'Saubere, bemaßte 2D-Grundrisse', popular: true },
  { id: 'plan3d', name: 'Grundriss 3D', icon: 'cube', price: 149, duration: 'Digital', desc: 'Fotorealistische 3D-Ansicht' },
  { id: 'matterport', name: 'Matterport', icon: 'scan', price: 389, duration: '1,5 Std.', desc: 'Begehbare Dollhouse-Tour' },
  { id: 'energy', name: 'Energieausweis', icon: 'bolt', price: 99, duration: 'Online', desc: 'Verbrauchs- oder Bedarfsausweis' },
  { id: 'copy', name: 'Exposé-Text', icon: 'text', price: 89, duration: 'Digital', desc: 'Verkaufsstarker Objekttext' },
];

const BUNDLES = [
  { id: 'basic', name: 'Basis', items: ['photo', 'plan2d'], save: 10, tagline: 'Für schnelle Einsteiger' },
  { id: 'smart', name: 'Smart', items: ['photo', 'plan2d', 'drone', 'copy'], save: 15, tagline: 'Unsere Empfehlung', recommended: true },
  { id: 'premium', name: 'Premium', items: ['photo', 'plan2d', 'plan3d', 'drone', 'video', 'tour360', 'copy'], save: 20, tagline: 'Für hochwertige Objekte' },
];

const PROVIDERS = [
  {
    id: 'p1',
    name: 'Lea Hartmann',
    studio: 'Hartmann Bildwerk',
    avatar: 'LH',
    location: 'Köln',
    distance: 4.2,
    rating: 4.9,
    reviews: 127,
    price: 289,
    priceRange: '240–320 €',
    responseHr: 2,
    specialties: ['Altbau', 'Reihenhaus', 'Innenräume'],
    certs: ['HDR-zertifiziert', 'DJI-lizenziert'],
    services: ['photo', 'drone', 'plan2d'],
    availability: ['2026-04-22', '2026-04-23', '2026-04-25'],
    matchScore: 96,
    matchReasons: [
      { label: 'Nur 4,2 km entfernt', weight: 'hoch' },
      { label: 'Altbau-Spezialistin', weight: 'hoch' },
      { label: 'Termin diese Woche verfügbar', weight: 'mittel' },
      { label: 'Preis im Budget', weight: 'mittel' },
    ],
    portfolio: 4,
    bio: 'Seit 8 Jahren spezialisiert auf warme, lebendige Innenraumfotografie. Arbeitet am liebsten mit Tageslicht.',
  },
  {
    id: 'p2',
    name: 'Tobias Renner',
    studio: 'Renner Media',
    avatar: 'TR',
    location: 'Bergisch Gladbach',
    distance: 11.8,
    rating: 4.8,
    reviews: 203,
    price: 249,
    priceRange: '210–280 €',
    responseHr: 1,
    specialties: ['Neubau', 'Gewerbe', 'Drohne'],
    certs: ['DJI-lizenziert', 'EU-Kenntnisnachweis A2'],
    services: ['photo', 'drone', 'video', 'plan2d'],
    availability: ['2026-04-21', '2026-04-24', '2026-04-26'],
    matchScore: 91,
    matchReasons: [
      { label: 'Reagiert in <1 Std.', weight: 'hoch' },
      { label: 'Drohne inklusive', weight: 'hoch' },
      { label: '11 km entfernt', weight: 'mittel' },
    ],
    portfolio: 4,
    bio: 'All-in-one Media-Team mit Schwerpunkt Drohne und Video. Schnelle Lieferung binnen 48 Std.',
  },
  {
    id: 'p3',
    name: 'Studio Nordlicht',
    studio: 'Nordlicht Kollektiv',
    avatar: 'SN',
    location: 'Leverkusen',
    distance: 14.3,
    rating: 5.0,
    reviews: 68,
    price: 340,
    priceRange: '290–380 €',
    responseHr: 4,
    specialties: ['Premium', 'Villa', 'Editorial'],
    certs: ['Architekturfoto-Zert.', 'Matterport Pro'],
    services: ['photo', 'video', 'tour360', 'matterport'],
    availability: ['2026-04-28', '2026-04-30'],
    matchScore: 88,
    matchReasons: [
      { label: 'Editorial-Qualität', weight: 'hoch' },
      { label: 'Bewertung 5,0', weight: 'mittel' },
      { label: 'Termin nächste Woche', weight: 'mittel' },
    ],
    portfolio: 4,
    bio: 'Kleines Kollektiv aus drei Fotograf·innen. Fokus auf hochwertige, editoriale Bildsprache.',
  },
  {
    id: 'p4',
    name: 'Marco Vitale',
    studio: 'Vitale Visuals',
    avatar: 'MV',
    location: 'Bonn',
    distance: 22.1,
    rating: 4.7,
    reviews: 94,
    price: 219,
    priceRange: '180–250 €',
    responseHr: 3,
    specialties: ['Wohnung', 'Studio', 'Schnell'],
    certs: ['DJI-lizenziert'],
    services: ['photo', 'drone', 'plan2d', 'copy'],
    availability: ['2026-04-22', '2026-04-23'],
    matchScore: 84,
    matchReasons: [
      { label: 'Günstigstes Angebot', weight: 'hoch' },
      { label: 'Sofort buchbar', weight: 'mittel' },
    ],
    portfolio: 4,
    bio: 'Effizient, pünktlich, freundlich. Ideal für Standard-Wohnungen im mittleren Segment.',
  },
  {
    id: 'p5',
    name: 'Anika Weiß',
    studio: 'Weiß Immobilienfoto',
    avatar: 'AW',
    location: 'Düsseldorf',
    distance: 38.4,
    rating: 4.9,
    reviews: 156,
    price: 310,
    priceRange: '260–340 €',
    responseHr: 2,
    specialties: ['Luxus', 'Historisch'],
    certs: ['HDR-zertifiziert'],
    services: ['photo', 'tour360', 'plan2d'],
    availability: ['2026-04-27', '2026-04-29'],
    matchScore: 79,
    matchReasons: [
      { label: 'Luxus-Erfahrung', weight: 'mittel' },
    ],
    portfolio: 4,
    bio: 'Spezialisiert auf historische und hochwertige Objekte. Ruhige, klassische Bildsprache.',
  },
];

window.IH_MEDIA = MEDIA_CATALOG;
window.IH_BUNDLES = BUNDLES;
window.IH_PROVIDERS = PROVIDERS;
